import "../style/TeamDetails.css";
import React, { useEffect, useRef, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Link, useParams } from "react-router-dom";
import Modal from "./Modal";
import GroupsIcon from "@mui/icons-material/Groups";
import Chart from "chart.js/auto";
import { Button, Col, Dropdown, Form } from "react-bootstrap";
import FormField from "./FormField";
import {
  calculateDiscountForTeam,
  createTeamCheckoutSession,
  isEmail,
} from "../constants/helper.js";
import {
  addMember,
  add_remove_Admins,
  removeMember,
} from "../slices/TeamsSlice.js";
import Swal from "sweetalert2";

const TeamDetails = () => {
  const { id } = useParams();
  const [showAddNewMemberModal, setShowAddNewMemberModal] = useState(false);
  const [showActivateteamModal, setShowActivateModal] = useState(false);
  const [selectedOption, setSelectedOption] = useState(true); //false for members, true for analytics
  const [totalPostsGenerated, setTotalPostsGenerated] = useState(0);
  const chartRef = useRef(null);
  const dispatch = useDispatch();
  const teamDetails = useSelector(
    (state) => state.Teams.find((obj) => obj.team._id === id)?.team
  );
  const { email } = useSelector((state) => state.User);

  const [formData, setFormData] = useState({
    emails: "",
  });

  useEffect(() => {
    if (teamDetails?.members && selectedOption) {
      const newChartData = [];
      const newChartLabels = [];
      const newTotalPostsGenerated = teamDetails.members.reduce(
        (total, member) => {
          const posts = member.posts;
          newChartData.push(posts);
          newChartLabels.push(member.email);
          return total + posts;
        },
        0
      );
      const ctx = document.getElementById("postsGenerated");
      chartRef.current = new Chart(ctx, {
        type: "bar",
        data: {
          labels: newChartLabels,
          datasets: [
            {
              label: "Posts Generated By Each User",
              data: newChartData,
            },
          ],
        },
      });

      setTotalPostsGenerated(newTotalPostsGenerated);

      return () => {
        if (chartRef.current) {
          chartRef.current.destroy();
        }
      };
    }
  }, [teamDetails, selectedOption]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const onClose = () => {
    setShowAddNewMemberModal(false);
    setShowActivateModal(false);
  };

  const handleAddNewMembers = (e) => {
    e.preventDefault();

    // Split the input into an array of email addresses
    const emails = formData.emails
      .split(/[,\s\n]+/)
      .filter((email) => email.trim() !== "" && isEmail(email));

    dispatch(addMember({ id, emails, adminEmail: email }));

    setFormData({
      ...formData,
      emails: "",
    });

    onClose();
  };

  const AddNewMemberModal = () => (
    <Modal
      heading={"Add a New Member"}
      subheading={"Add new members to team to work in collaboration"}
      onClose={onClose}
    >
      <Form>
        <FormField
          label={"Add Users (comma, space, or newline separated):"}
          onChange={handleChange}
          placeholder={"Enter new member email(s)"}
          value={formData.emails}
          name={"emails"}
          as={"textarea"}
        />

        <Button
          onClick={handleAddNewMembers}
          variant="primary"
          className="submit w-100"
        >
          Add Users
        </Button>
      </Form>
    </Modal>
  );

  const ActivateTeamModal = () => (
    <Modal
      heading={"Activate Your Team"}
      subheading={"Activating your team would allow you to add members"}
      onClose={onClose}
    >
      <Col className="row d-flex flex-row justify-content-evenly w-100">
        <div style={{ height: "50px" }} />
        <div className="col-12 col-md-6 col-lg-6 ">
          <div
            className="card p-3"
            style={{
              textAlign: "left",
            }}
          >
            <h4>Pro Package</h4>
            <p style={{ color: "#6B7280" }}>To help you grow</p>

            <h3>
              {(
                parseInt(teamDetails.teamSize) *
                (49.99 - 49.99 * calculateDiscountForTeam(teamDetails.teamSize))
              ).toFixed(2)}
              <span style={{ color: "#6B7280" }}>/month</span>
            </h3>
            <h3>
              <span
                style={{
                  color: "#d40000",
                  marginLeft: 0,
                  textDecoration: "line-through",
                }}
              >
                {(parseInt(teamDetails.teamSize) * 49.99).toFixed(2)}
              </span>
            </h3>
            <button
              onClick={() =>
                createTeamCheckoutSession(
                  teamDetails._id,
                  "price_1OYcCdJOtdUfVp0DfkBSsqof"
                )
              }
              className="btn btn-primary plan"
            >
              Choose Plan
            </button>
          </div>
        </div>
        <div className="col-12 col-md-6 col-lg-6 ">
          <div
            className="card p-3"
            style={{
              textAlign: "left",
            }}
          >
            <h4>Pro Package</h4>
            <p style={{ color: "#6B7280" }}>To help you grow</p>
            <h3>
              {(
                parseInt(teamDetails.teamSize) *
                (499.99 -
                  499.99 * calculateDiscountForTeam(teamDetails.teamSize))
              ).toFixed(2)}
              <span style={{ color: "#6B7280" }}>/year</span>
            </h3>
            <h4>
              <span
                style={{
                  color: "#d40000",
                  marginLeft: 0,
                  textDecoration: "line-through",
                }}
              >
                {(parseInt(teamDetails.teamSize) * 499.99).toFixed(2)}
              </span>
            </h4>
            <button
              onClick={() =>
                createTeamCheckoutSession(
                  teamDetails._id,
                  "price_1OYcCdJOtdUfVp0DfkBSsqof"
                )
              }
              className="btn btn-primary plan"
            >
              Choose Plan
            </button>
          </div>
        </div>
        <div style={{ height: "50px" }} />
      </Col>
    </Modal>
  );

  function ShowModal() {
    if (teamDetails.status === "inactive") {
      setShowActivateModal(true);
    } else setShowAddNewMemberModal(true);
  }

  const AddNewMemberButton = () => (
    <Link
      style={{ textDecoration: "none", color: "white" }}
      className="new-team-member"
    >
      <button style={{ position: "relative", width: 260 }} onClick={ShowModal}>
        Add New Member
        <GroupsIcon className="groupsIcon" sx={{ fontSize: 40 }} />
      </button>
    </Link>
  );

  const handleMemberFunctions = ({ email, type }) => {
    Swal.fire({
      title: "Are you sure?",
      text: "You won't be able to revert this!",
      icon: "warning",
      showCancelButton: true,
      confirmButtonColor: "#3085d6",
      cancelButtonColor: "#d33",
      confirmButtonText:
        type === 2 ? "Make Admin" : type === 1 ? "Remove Admin" : "Remove",
    }).then((result) => {
      if (result.isConfirmed) {
        switch (type) {
          case 1:
            dispatch(add_remove_Admins({ id, email, type: 1 }));
            break;
          case 2:
            dispatch(add_remove_Admins({ id, email, type: 2 }));
            break;
          case 3:
            dispatch(removeMember({ id, email, type: true }));
            break;

          default:
            break;
        }
      }
    });
  };

  const handleResendInvite = ({ email }) => {
    setFormData({ email });
    handleAddNewMembers();
  };

  const DisplayPersons = ({ Person, isAdmin, type, owner }) => (
    //type= => true for member, false for pending member
    <div className="team-box">
      <div className="team-box-left">
        {Person.fullName ? (
          <>
            <p className="team-name">
              {Person.fullName}
              <span className="member-properties">
                {isAdmin && "Admin"}
                {"         "}
                {Person.email === owner && "Owner"}
              </span>
            </p>
            <p className="team-email">{Person.email}</p>
          </>
        ) : (
          <div className="pending-members">
            <p className="team-name">{Person.email}</p>
            {type && <p className="member-properties">Invite Sent</p>}
          </div>
        )}
      </div>

      {Person.email === email ||
      Person.email === owner ? null : Person.fullName ? (
        <Dropdown>
          <Dropdown.Toggle id="dropdown-basic" />
          <Dropdown.Menu>
            {isAdmin ? (
              <Dropdown.Item
                onClick={() =>
                  handleMemberFunctions({ email: Person.email, type: 1 })
                }
              >
                Remove Admin
              </Dropdown.Item>
            ) : (
              <Dropdown.Item
                onClick={() =>
                  handleMemberFunctions({ email: Person.email, type: 2 })
                }
              >
                Make Admin
              </Dropdown.Item>
            )}
            <Dropdown.Item
              onClick={() =>
                handleMemberFunctions({ email: Person.email, type: 3 })
              }
            >
              Remove
            </Dropdown.Item>
          </Dropdown.Menu>
        </Dropdown>
      ) : (
        <Dropdown>
          <Dropdown.Toggle id="dropdown-basic" />
          <Dropdown.Menu>
            <Dropdown.Item
              onClick={() => {
                handleResendInvite({ email: Person.email });
              }}
            >
              Resend Invite
            </Dropdown.Item>
            <Dropdown.Item
              onClick={() =>
                handleMemberFunctions({ email: Person.email, type: 3 })
              }
            >
              Remove
            </Dropdown.Item>
          </Dropdown.Menu>
        </Dropdown>
      )}
    </div>
  );

  return (
    <div className="teams-details-container">
      <div className="teams-details-header">
        <div className="center-info">
          <h1>{teamDetails && teamDetails.name}</h1>
        </div>
        {/* <div className="left-info">
          <div>Team Size: {teamDetails.teamSize}</div>
          <div>No. of Members: {teamDetails.members.length}</div>
        </div> */}
      </div>

      <div>
        <div className="members">
          <div className="memberButtons">
            <h3
              style={{
                marginRight: "1rem",
                borderBottom: selectedOption ? "2px solid red" : "none",
              }}
              className="h3Buttons"
              onClick={() => setSelectedOption(!selectedOption)}
            >
              Analytics
            </h3>

            <h3
              className="h3Buttons"
              style={{
                borderBottom: !selectedOption ? "2px solid red" : "none",
              }}
              onClick={() => setSelectedOption(!selectedOption)}
            >
              Members
            </h3>
          </div>
          {teamDetails?.members?.length >= 1 && <AddNewMemberButton />}
        </div>

        {selectedOption ? (
          <div style={{ height: 300, width: "100%" }}>
            <h5>Total Posts Generated by Team: {totalPostsGenerated}</h5>
            <canvas
              style={{ height: "100%", width: "100%" }}
              id="postsGenerated"
            />
          </div>
        ) : (
          <div className="display-teams">
            <>
              {teamDetails?.members?.map((member) => (
                <DisplayPersons
                  owner={teamDetails.owner}
                  Person={member}
                  key={member._id}
                  isAdmin={teamDetails.admins.some(
                    (obj) => obj.email === member.email
                  )}
                />
              ))}

              {teamDetails?.pendingMembers?.map((member) => (
                <DisplayPersons
                  owner={teamDetails.owner}
                  Person={member}
                  key={member._id}
                  type={true}
                />
              ))}
            </>
          </div>
        )}
      </div>
      {showAddNewMemberModal && AddNewMemberModal()}
      {showActivateteamModal && ActivateTeamModal()}
    </div>
  );
};

export default TeamDetails;
